const PptxGenJS = require("pptxgenjs");

async function createPresentation() {
  let pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_16x9";
  pptx.author = "Generated by AI";
  pptx.company = "Micro-Feedback System";
  pptx.title = "Micro-Feedback System Website";

  // Fonts & Colors
  const fontTitle = "Montserrat";
  const fontBody = "Poppins";
  const colorBg = "0F172A";       // Slate 900
  const colorPrimary = "38BDF8";  // Sky 400
  const colorText = "F8FAFC";     // Slate 50
  const colorSub = "94A3B8";      // Slate 400
  const colorAccent = "818CF8";   // Indigo 400

  // Master Slide Definition
  pptx.defineSlideMaster({
    title: "MASTER",
    background: { color: colorBg },
    objects: [
      { rect: { x: 0, y: 0, w: "100%", h: 0.1, fill: { color: colorPrimary } } }, // Top gradient/line
      { text: { text: "Micro-Feedback System", options: { x: 0.5, y: 7.0, w: 4, h: 0.3, color: colorSub, fontSize: 10, fontFace: fontBody } } },
    ]
  });

  const addHeader = (slide, titleText) => {
    slide.addText(titleText, { x: 0.5, y: 0.5, w: 8, h: 0.8, fontSize: 36, fontFace: fontTitle, color: colorText, bold: true });
    slide.addShape(pptx.ShapeType.line, { x: 0.5, y: 1.3, w: 2.5, h: 0, line: { color: colorPrimary, width: 3 } });
  };

  const createList = (items) => {
    return items.map(text => ({ text, options: { bullet: { type: "bullet", color: colorPrimary }, fontSize: 22, fontFace: fontBody, color: colorText, breakLine: true } }));
  };

  // --- Slide 1: Title Slide ---
  let slide1 = pptx.addSlide({ masterName: "MASTER" });
  slide1.addText("Micro-Feedback System Website", { x: 1, y: 2.5, w: 8, h: 1, fontSize: 48, fontFace: fontTitle, color: colorText, bold: true });
  slide1.addText("Enhancing Learning Through Continuous Feedback", { x: 1, y: 3.5, w: 8, h: 0.5, fontSize: 24, fontFace: fontBody, color: colorPrimary });
  slide1.addText("Presented by: [Your Name]\nProject Presentation", { x: 1, y: 5.5, w: 8, h: 1, fontSize: 18, fontFace: fontBody, color: colorSub });

  // --- Slide 2: Introduction ---
  let slide2 = pptx.addSlide({ masterName: "MASTER" });
  addHeader(slide2, "Introduction");
  slide2.addText(createList([
    "A web-based platform for students and teachers",
    "Designed to collect quick and structured feedback",
    "Improves communication and learning efficiency"
  ]), { x: 0.5, y: 2, w: 8.5, h: 3, lineSpacing: 44 });

  // --- Slide 3: Problem Statement & Solution ---
  let slide3 = pptx.addSlide({ masterName: "MASTER" });
  addHeader(slide3, "Problem Statement & Solution");
  slide3.addText("Problems:", { x: 0.5, y: 1.6, w: 4, h: 0.5, fontSize: 24, fontFace: fontTitle, color: "EF4444", bold: true });
  slide3.addText(createList([
    "Delayed or missing feedback",
    "Lack of student engagement",
    "No proper doubt clarification system"
  ]), { x: 0.5, y: 2.2, w: 4.5, h: 2, lineSpacing: 32 });

  slide3.addText("Solution:", { x: 5.5, y: 1.6, w: 4, h: 0.5, fontSize: 24, fontFace: fontTitle, color: "22C55E", bold: true });
  slide3.addText(createList([
    "Micro-feedback with instant response system",
    "Structured dashboards for users",
    "Integrated doubt clearing module"
  ]), { x: 5.5, y: 2.2, w: 4.5, h: 2, lineSpacing: 32 });

  // --- Slide 4: System Overview ---
  let slide4 = pptx.addSlide({ masterName: "MASTER" });
  addHeader(slide4, "System Overview");
  slide4.addText("Workflow:", { x: 0.5, y: 1.8, w: 8, h: 0.5, fontSize: 24, fontFace: fontTitle, color: colorPrimary, bold: true });
  
  // Custom Flowchart
  let flowSteps = ["Login", "Dashboard", "Units", "Feedback", "Doubts"];
  flowSteps.forEach((step, i) => {
    slide4.addShape(pptx.ShapeType.rect, { x: 0.5 + (i * 1.8), y: 2.5, w: 1.5, h: 0.8, fill: { color: "1E293B" }, line: { color: colorPrimary, width: 2 } });
    slide4.addText(step, { x: 0.5 + (i * 1.8), y: 2.5, w: 1.5, h: 0.8, align: "center", color: colorText, fontFace: fontBody, fontSize: 18, bold: true });
    if (i < flowSteps.length - 1) {
      slide4.addShape(pptx.ShapeType.rightArrow, { x: 2.05 + (i * 1.8), y: 2.8, w: 0.2, h: 0.2, fill: { color: colorSub } });
    }
  });

  slide4.addText(createList([
    "Simple and intuitive navigation",
    "Smooth user experience"
  ]), { x: 0.5, y: 4, w: 8.5, h: 1.5, lineSpacing: 32 });

  // --- Slide 5: Login System ---
  let slide5 = pptx.addSlide({ masterName: "MASTER" });
  slide5.addText("Login Module", { x: 0.5, y: 0.5, w: 3, h: 0.4, fontSize: 16, fontFace: fontBody, color: colorAccent });
  addHeader(slide5, "Login System");
  slide5.addText(createList([
    "User login with email and password",
    "Clean and minimal interface",
    "Secure authentication"
  ]), { x: 0.5, y: 2.2, w: 8.5, h: 3, lineSpacing: 44 });

  // --- Slide 6: Password Reset & OTP ---
  let slide6 = pptx.addSlide({ masterName: "MASTER" });
  slide6.addText("Login Module", { x: 0.5, y: 0.5, w: 3, h: 0.4, fontSize: 16, fontFace: fontBody, color: colorAccent });
  addHeader(slide6, "Password Reset & OTP");
  slide6.addText(createList([
    "Forgot password option",
    "OTP sent to registered email",
    "OTP verification process",
    "Reset password and re-login"
  ]), { x: 0.5, y: 2.2, w: 8.5, h: 3, lineSpacing: 44 });

  // --- Slide 7: Student Dashboard ---
  let slide7 = pptx.addSlide({ masterName: "MASTER" });
  slide7.addText("Student Module", { x: 0.5, y: 0.5, w: 3, h: 0.4, fontSize: 16, fontFace: fontBody, color: colorAccent });
  addHeader(slide7, "Student Dashboard");
  slide7.addText(createList([
    "Sections: Units, Feedback, Doubts",
    "Easy navigation and clean layout",
    "Student-friendly design"
  ]), { x: 0.5, y: 2.2, w: 8.5, h: 3, lineSpacing: 44 });

  // --- Slide 8: Student Features ---
  let slide8 = pptx.addSlide({ masterName: "MASTER" });
  slide8.addText("Student Module", { x: 0.5, y: 0.5, w: 3, h: 0.4, fontSize: 16, fontFace: fontBody, color: colorAccent });
  addHeader(slide8, "Student Features");
  slide8.addText(createList([
    "Access unit-wise notes",
    "Answer 6 feedback questions",
    "Post and track doubts",
    "Continuous learning support"
  ]), { x: 0.5, y: 2.2, w: 8.5, h: 3, lineSpacing: 44 });

  // --- Slide 9: Teacher Dashboard ---
  let slide9 = pptx.addSlide({ masterName: "MASTER" });
  slide9.addText("Teacher Module", { x: 0.5, y: 0.5, w: 3, h: 0.4, fontSize: 16, fontFace: fontBody, color: colorAccent });
  addHeader(slide9, "Teacher Dashboard");
  slide9.addText(createList([
    "Central control panel",
    "Monitor student activity",
    "Manage learning content"
  ]), { x: 0.5, y: 2.2, w: 8.5, h: 3, lineSpacing: 44 });

  // --- Slide 10: Teacher Features ---
  let slide10 = pptx.addSlide({ masterName: "MASTER" });
  slide10.addText("Teacher Module", { x: 0.5, y: 0.5, w: 3, h: 0.4, fontSize: 16, fontFace: fontBody, color: colorAccent });
  addHeader(slide10, "Teacher Features");
  slide10.addText(createList([
    "Upload unit materials",
    "Analyze feedback responses",
    "Respond to student doubts",
    "Track performance insights"
  ]), { x: 0.5, y: 2.2, w: 8.5, h: 3, lineSpacing: 44 });

  // --- Slide 11: Feedback System ---
  let slide11 = pptx.addSlide({ masterName: "MASTER" });
  slide11.addText("Core System", { x: 0.5, y: 0.5, w: 3, h: 0.4, fontSize: 16, fontFace: fontBody, color: colorAccent });
  addHeader(slide11, "Feedback System");
  slide11.addText(createList([
    "6 structured questions",
    "Quick and easy responses",
    "Helps measure understanding"
  ]), { x: 0.5, y: 2.2, w: 8.5, h: 3, lineSpacing: 44 });

  // --- Slide 12: Doubt Clearing System ---
  let slide12 = pptx.addSlide({ masterName: "MASTER" });
  slide12.addText("Core System", { x: 0.5, y: 0.5, w: 3, h: 0.4, fontSize: 16, fontFace: fontBody, color: colorAccent });
  addHeader(slide12, "Doubt Clearing System");
  slide12.addText(createList([
    "Students submit queries",
    "Teachers provide answers",
    "Improves clarity and interaction"
  ]), { x: 0.5, y: 2.2, w: 8.5, h: 3, lineSpacing: 44 });

  // --- Slide 13: Insights & Tracking ---
  let slide13 = pptx.addSlide({ masterName: "MASTER" });
  slide13.addText("Core System", { x: 0.5, y: 0.5, w: 3, h: 0.4, fontSize: 16, fontFace: fontBody, color: colorAccent });
  addHeader(slide13, "Insights & Tracking");
  slide13.addText(createList([
    "Monitor student performance",
    "Identify weak areas",
    "Improve teaching strategies"
  ]), { x: 0.5, y: 2.2, w: 8.5, h: 3, lineSpacing: 44 });

  // --- Slide 14: Common Features ---
  let slide14 = pptx.addSlide({ masterName: "MASTER" });
  addHeader(slide14, "Common Features");
  
  let features = [
    { text: "Secure login", color: "F59E0B" },
    { text: "Dashboard-based navigation", color: "10B981" },
    { text: "Real-time interaction", color: "3B82F6" },
    { text: "User-friendly interface", color: "8B5CF6" }
  ];

  features.forEach((f, i) => {
    let row = Math.floor(i / 2);
    let col = i % 2;
    slide14.addShape(pptx.ShapeType.roundRect, { x: 0.5 + (col * 4.5), y: 2.2 + (row * 1.5), w: 4, h: 1, fill: { color: "1E293B" }, rectRadius: 0.1 });
    slide14.addShape(pptx.ShapeType.rect, { x: 0.5 + (col * 4.5), y: 2.2 + (row * 1.5), w: 0.15, h: 1, fill: { color: f.color } });
    slide14.addText(f.text, { x: 0.8 + (col * 4.5), y: 2.2 + (row * 1.5), w: 3.5, h: 1, fontSize: 20, fontFace: fontBody, color: colorText, bold: true });
  });

  // --- Slide 15: Conclusion ---
  let slide15 = pptx.addSlide({ masterName: "MASTER" });
  addHeader(slide15, "Conclusion");
  slide15.addText(createList([
    "Enhances student-teacher communication",
    "Provides structured feedback system",
    "Improves overall learning experience"
  ]), { x: 0.5, y: 2.2, w: 8.5, h: 3, lineSpacing: 44 });

  // --- Slide 16: Future Enhancements ---
  let slide16 = pptx.addSlide({ masterName: "MASTER" });
  addHeader(slide16, "Future Enhancements");
  slide16.addText(createList([
    "AI-based feedback analysis",
    "Real-time chat system",
    "Mobile application development"
  ]), { x: 0.5, y: 2.2, w: 8.5, h: 3, lineSpacing: 44 });

  // Generate PPT
  await pptx.writeFile({ fileName: "MicroFeedback_Presentation.pptx" });
  console.log("Successfully created MicroFeedback_Presentation.pptx");
}

createPresentation().catch(err => {
  console.error("Error generating presentation:", err);
});
